#remote_theme: pages-themes/leap-day
remote_theme : pages-themes/minimal
# minimal_mistakes_skin : "contrast" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
plugins:
  - jekyll-remote-theme
